version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      ports:
        -3306:3306
      networks:
        -app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge